accounts:
  - name: alice
    coins: ["100000000uatom", "1000000000000000dbs"]
  - name: bob
    coins: ["50000000dbs"]
validator:
  name: alice
  staked: "100000000dbs"
faucet:
  name: bob 
  coins: ["10dbs"]
build:
  binary: "evmosd"
init:
  home: "$HOME/.evmosd"
  app:
    evm-rpc:
      address: "0.0.0.0:8545"     # change the JSON-RPC address and port
      ws-address: "0.0.0.0:8546"  # change the JSON-RPC websocket address and port
genesis:
  chain_id: "dbsd_9000-1"
  app_state:
    staking:
      params:
        bond_denom: "dbs"
    mint:
      params:
        mint_denom: "dbs"
    crisis:
      constant_fee:
        denom: "dbs"
    gov:
      deposit_params:
        min_deposit:
          - amount: "100000"
            denom: "dbs"
    evm:
      params:
        evm_denom: "dbs"
